# Generated by Django 6.0.2 on 2026-02-21 10:28

import django.db.models.deletion
import facturx_fr.models.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='numéro de facture')),
                ('issue_date', models.DateField(verbose_name="date d'émission")),
                ('due_date', models.DateField(blank=True, null=True, verbose_name="date d'échéance")),
                ('type_code', models.CharField(db_default='380', max_length=3, verbose_name='type de document')),
                ('currency', models.CharField(db_default='EUR', max_length=3, verbose_name='devise')),
                ('operation_category', models.CharField(choices=[(facturx_fr.models.enums.OperationCategory['DELIVERY'], 'Livraison de biens'), (facturx_fr.models.enums.OperationCategory['SERVICE'], 'Prestation de services'), (facturx_fr.models.enums.OperationCategory['MIXED'], 'Mixte')], max_length=10, verbose_name="catégorie de l'opération")),
                ('seller_name', models.CharField(max_length=200, verbose_name='raison sociale vendeur')),
                ('seller_siren', models.CharField(max_length=9, verbose_name='SIREN vendeur')),
                ('seller_vat_number', models.CharField(blank=True, default='', max_length=20, verbose_name='n° TVA vendeur')),
                ('seller_street', models.CharField(max_length=200, verbose_name='adresse vendeur')),
                ('seller_city', models.CharField(max_length=100, verbose_name='ville vendeur')),
                ('seller_postal_code', models.CharField(max_length=10, verbose_name='code postal vendeur')),
                ('seller_country_code', models.CharField(db_default='FR', max_length=2, verbose_name='pays vendeur')),
                ('buyer_name', models.CharField(max_length=200, verbose_name='raison sociale acheteur')),
                ('buyer_siren', models.CharField(max_length=9, verbose_name='SIREN acheteur')),
                ('buyer_vat_number', models.CharField(blank=True, default='', max_length=20, verbose_name='n° TVA acheteur')),
                ('buyer_street', models.CharField(max_length=200, verbose_name='adresse acheteur')),
                ('buyer_city', models.CharField(max_length=100, verbose_name='ville acheteur')),
                ('buyer_postal_code', models.CharField(max_length=10, verbose_name='code postal acheteur')),
                ('buyer_country_code', models.CharField(db_default='FR', max_length=2, verbose_name='pays acheteur')),
                ('payment_iban', models.CharField(blank=True, default='', max_length=34, verbose_name='IBAN')),
                ('payment_bic', models.CharField(blank=True, default='', max_length=11, verbose_name='BIC')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('200', 'Déposée'), ('201', 'Émise'), ('202', 'Reçue'), ('203', 'Mise à disposition'), ('204', 'Prise en charge'), ('205', 'Approuvée'), ('206', 'Partiellement approuvée'), ('207', 'En litige'), ('208', 'Suspendue'), ('209', "Rejetée à l'émission"), ('210', 'Refusée'), ('211', 'Paiement transmis'), ('212', 'Rejetée à la réception'), ('213', 'Encaissée'), ('214', 'Complétée')], db_default='draft', max_length=10, verbose_name='statut')),
                ('pdp_invoice_id', models.CharField(blank=True, default='', max_length=100, verbose_name='identifiant PDP')),
                ('xml_file', models.FileField(blank=True, upload_to='facturx/xml/', verbose_name='fichier XML')),
                ('pdf_file', models.FileField(blank=True, upload_to='facturx/pdf/', verbose_name='fichier PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
            ],
            options={
                'verbose_name': 'facture',
                'verbose_name_plural': 'factures',
                'indexes': [models.Index(fields=['status', 'issue_date'], name='idx_status_issue_date'), models.Index(fields=['seller_siren'], name='idx_seller_siren'), models.Index(fields=['buyer_siren'], name='idx_buyer_siren')],
                'constraints': [models.CheckConstraint(condition=models.Q(('seller_siren__regex', '^\\d{9}$')), name='valid_seller_siren'), models.CheckConstraint(condition=models.Q(('buyer_siren__regex', '^\\d{9}$')), name='valid_buyer_siren')],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField(verbose_name='numéro de ligne')),
                ('description', models.CharField(max_length=500, verbose_name='désignation')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='quantité')),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='prix unitaire HT')),
                ('vat_rate', models.DecimalField(db_default='20.00', decimal_places=2, max_digits=5, verbose_name='taux de TVA (%)')),
                ('vat_category', models.CharField(db_default='S', max_length=3, verbose_name='catégorie TVA')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='facturx_fr.invoice', verbose_name='facture')),
            ],
            options={
                'verbose_name': 'ligne de facture',
                'verbose_name_plural': 'lignes de facture',
                'ordering': ['line_number'],
            },
        ),
    ]
